version: '3.8'

services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buildpro
    volumes:
      - polls_pg_data:/bitnami/postgresql
    
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      npx prisma migrate dev --schema=./prisma/schema.prisma &&
      npm run dev
      "

volumes:
  polls_pg_data:
